version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pokemon-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Liliana0912
      POSTGRES_DB: pokemon_db
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokemon-net

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: pokemon-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/pokemon_db
    depends_on:
      - db
    networks:
      - pokemon-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pokemon-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pokemon-net

networks:
  pokemon-net:
    driver: bridge

volumes:
  postgres_data:
